version: 2

sources:
  - name: silver_screen
    database: silver_screen
    schema: public
    tables: 
      - name: invoices
        description: Contains raw information on invoices for rentals on the locations.
      - name: movie_catalog
        description: Contains raw information on the movies screened in 2024 by the locations.
      - name: nj_001
        description: Contains raw information on ticketing from location 001.
      - name: nj_002
        description: Contains raw information on ticketing from location 002.
      - name: nj_003
        description: Contains raw information on ticketing from location 003.
models:
  - name: movies_clean
    description: Replaces null values in the genre column with 'Unknown'.
    columns:
      - name: movie_id
        tests:
          - not_null
          - unique
      - name: genre
        tests:
          - not_null
  - name: invoices_clean
    description: changes caption of location_id to lower.
    columns:
      - name: location_id
        tests:
        - not_null
  - name: monthly_aggregation_001.sql
    description: Aggregates ticket sales data from location 001 (amount and revenue) per movie at the month level.
    columns:
      - name: month
        description: The first day of the month (e.g., 2025-02-01).
        tests:
          - not_null
      - name: movie_id
        tests:
          - not_null
          - relationships:
              field: <movie_id>
              to: ref('movies_clean')
      - name: total_tickets
        description: Sum of tickets sold per month and movie.
        tests:
          - not_null
      - name: total_revenue
        description: Sum of ticket sales per month and movie.
        tests:
          - not_null
  - name: monthly_aggregation_002.sql
    description: Aggregates ticket sales data from location 002 (amount and revenue) per movie at the month level.
    columns:
      - name: month
        description: The first day of the month (e.g., 2025-02-01).
        tests:
          - not_null
      - name: movie_id
        tests:
          - not_null
          - relationships:
              field: <movie_id>
              to: ref('movies_clean')
      - name: total_tickets
        description: Sum of tickets sold per month and movie.
        tests:
          - not_null
      - name: total_revenue
        description: Sum of ticket sales per month and movie.
        tests:
          - not_null
  - name: monthly_aggregation_003.sql
    description: Aggregates ticket sales data from location 003 (amount and revenue) per movie at the month level.
    columns:
      - name: month
        description: The first day of the month (e.g., 2025-02-01).
        tests:
          - not_null
      - name: movie_id
        tests:
          - not_null
          - relationships:
              field: <movie_id>
              to: ref('movies_clean')
      - name: total_tickets
        description: Sum of tickets sold per month and movie.
        tests:
          - not_null
      - name: total_revenue
        description: Sum of ticket sales per month and movie.
        tests:
          - not_null
  - name: union_locations
    description: Unifies cleaned and aggregated data at the movie and month level from 
      three locations and adds the location identifier.
    columns:
      - name: location_id
        description: Identifies the location according to the original table.
        tests:
          - not_null
          - relationships:
              field: <location_id>
              to: source('silver_scree', 'invoices')
      - name: movie_id
        tests:
          - not_null
          - relationships:
              field: <movie_id>
              to: ref('movies_clean')
     
          